force-app/main/default/objects/ConfigSetting__mdt/ConfigSetting__mdt.object-meta.xml
<CustomObject>
    <label>ConfigSetting</label>
    <pluralLabel>ConfigSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConfigSetting__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boolean</fullName>
                <default>true</default>
                <label>Boolean</label>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date Time</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>String</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfigSetting__mdt/fields/Deprecated__c.field-meta.xml
<CustomField>
    <fullName>Deprecated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deprecated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConfigSetting__mdt/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ManageConfigurationDetailsCls.cls
//This class is used by other classes where the value is needed far a specific data type
public class ManageConfigurationDetailsCls {
    
    public static WrapperDetails getDataTypeValue(string dataType){
        WrapperDetails wrapRec;
        try{
            
            if(dataType != null){
                for(ConfigSetting__mdt metadataRecord : [Select id,DeveloperName,Label,Data_Type__c,Deprecated__c,Value__c,Version__c from ConfigSetting__mdt where Data_Type__c =:dataType and Deprecated__c = false order by Version__c desc limit 1 ]){
                    wrapRec = new WrapperDetails();
                    if(dataType == 'Date'){
                        wrapRec.dateValue = date.parse(metadataRecord.Value__c);
                    }else if (dataType == 'String'){
                        wrapRec.stringValue = metadataRecord.Value__c;
                    } else if (dataType == 'Boolean'){
                        wrapRec.booleanValue = Boolean.valueOf(metadataRecord.Value__c);
                    } else if (dataType == 'Number'){
                        wrapRec.integerValue = Integer.valueOf(metadataRecord.Value__c);
                    }
                }
                
            }  
            
        }catch(exception e){
            system.debug('Exception Encountered>>'+e);
        }
        system.debug(wrapRec);
        return wrapRec;  
    }
    
    public class WrapperDetails{
        public Boolean booleanValue;
        public Integer integerValue;
        public Date dateValue; 
        public String stringValue ; 
    }
    
}